default: &default
    adapter: postgresql
    encoding: unicode
    username: vinhas
    password: vinhas
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
    <<: *default
    database: parking_control_api_development

test:
    <<: *default
    database: parking_control_api_test

production:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
    database: parking_control_api_production
